---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "English Test Generator"
keywords:    "english, test, learning, making, generating-tests, english-learning, school, cirriculum, english test generator, delirium products"
description: "Generate English tests with ease!"
source_link: "https://github.com/DeliriumProducts/EnglishTestGenerator"
favicon:     "img/Dtafalonso-Android-Lollipop-Dictionary.ico"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#ffffff'
  grey:      '#ebebeb'
  red:       '#d94235'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  pink:      '#e18d87'

kramdown:
  auto_ids:  false
